// Package controller provides a client adapter for probe_controller admin HTTP/WebSocket API.
// It migrates the controller session login and proxy capabilities (PKG-W2-01).
// Default controller URL: http://127.0.0.1:15030
package controller

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"
)

const (
	defaultControllerURL = "http://127.0.0.1:15030"
	clientTimeout        = 15 * time.Second
)

// Session holds an authenticated controller session (sessionToken returned by login).
type Session struct {
	mu          sync.RWMutex
	baseURL     string
	token       string
	httpClient  *http.Client
}

// SessionLoginResult is returned by Login.
type SessionLoginResult struct {
	OK      bool   `json:"ok"`
	Token   string `json:"token,omitempty"`
	Message string `json:"message"`
}

// NewSession creates a Session for the given controller base URL.
func NewSession(baseURL string) *Session {
	b := normalizeBaseURL(baseURL)
	return &Session{
		baseURL:    b,
		httpClient: &http.Client{Timeout: clientTimeout},
	}
}

// Login authenticates against the controller admin API using a nonce signature
// generated by the local admin private key (delegated to the caller via signFn).
// signFn must return base64-encoded Ed25519 signature of the nonce.
func (s *Session) Login(ctx context.Context, signFn func(nonce string) (string, error)) (SessionLoginResult, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	// Step 1: fetch nonce.
	nonceURL := s.baseURL + "/api/admin/auth/nonce"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, nonceURL, nil)
	if err != nil {
		return SessionLoginResult{}, fmt.Errorf("build nonce request: %w", err)
	}
	req.Header.Set("X-Forwarded-Proto", "https")
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return SessionLoginResult{}, fmt.Errorf("fetch nonce: %w", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return SessionLoginResult{}, fmt.Errorf("fetch nonce HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}

	var nonceResp struct {
		Nonce string `json:"nonce"`
	}
	if err := json.Unmarshal(body, &nonceResp); err != nil {
		return SessionLoginResult{}, fmt.Errorf("parse nonce response: %w", err)
	}
	nonce := strings.TrimSpace(nonceResp.Nonce)
	if nonce == "" {
		return SessionLoginResult{}, fmt.Errorf("controller returned empty nonce")
	}

	// Step 2: sign nonce.
	signature, err := signFn(nonce)
	if err != nil {
		return SessionLoginResult{}, fmt.Errorf("sign nonce: %w", err)
	}

	// Step 3: submit signature to get session token.
	loginURL := s.baseURL + "/api/admin/auth/login"
	payload := map[string]string{"nonce": nonce, "signature": signature}
	payloadBytes, _ := json.Marshal(payload)
	loginReq, err := http.NewRequestWithContext(ctx, http.MethodPost, loginURL, strings.NewReader(string(payloadBytes)))
	if err != nil {
		return SessionLoginResult{}, fmt.Errorf("build login request: %w", err)
	}
	loginReq.Header.Set("Content-Type", "application/json")
	loginReq.Header.Set("X-Forwarded-Proto", "https")
	loginResp, err := s.httpClient.Do(loginReq)
	if err != nil {
		return SessionLoginResult{}, fmt.Errorf("controller login: %w", err)
	}
	defer loginResp.Body.Close()
	loginBody, _ := io.ReadAll(io.LimitReader(loginResp.Body, 4096))
	if loginResp.StatusCode < 200 || loginResp.StatusCode >= 300 {
		return SessionLoginResult{}, fmt.Errorf("controller login HTTP %d: %s", loginResp.StatusCode, strings.TrimSpace(string(loginBody)))
	}

	var tokenResp struct {
		Token   string `json:"token"`
		Message string `json:"message"`
	}
	if err := json.Unmarshal(loginBody, &tokenResp); err != nil {
		return SessionLoginResult{}, fmt.Errorf("parse login response: %w", err)
	}
	token := strings.TrimSpace(tokenResp.Token)
	if token == "" {
		return SessionLoginResult{}, fmt.Errorf("controller returned empty session token")
	}

	s.token = token
	return SessionLoginResult{
		OK:      true,
		Token:   token,
		Message: strings.TrimSpace(tokenResp.Message),
	}, nil
}

// Token returns the current session token (empty if not logged in).
func (s *Session) Token() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.token
}

// BaseURL returns the configured controller base URL.
func (s *Session) BaseURL() string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.baseURL
}

// UpdateSession replaces the base URL and token (used when the frontend passes
// a pre-established controller session).
func (s *Session) UpdateSession(baseURL, token string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if b := normalizeBaseURL(baseURL); b != "" {
		s.baseURL = b
	}
	s.token = strings.TrimSpace(token)
}

// AuthorizedGet performs a GET against the controller API using the session token.
func (s *Session) AuthorizedGet(ctx context.Context, path string) ([]byte, int, error) {
	s.mu.RLock()
	base := s.baseURL
	token := s.token
	s.mu.RUnlock()

	rawURL := base + path
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("X-Forwarded-Proto", "https")

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	return body, resp.StatusCode, err
}

// AuthorizedPost performs a POST against the controller API using the session token.
// bodyJSON may be nil for empty-body requests.
func (s *Session) AuthorizedPost(ctx context.Context, path string, bodyJSON []byte) ([]byte, int, error) {
	s.mu.RLock()
	base := s.baseURL
	token := s.token
	s.mu.RUnlock()

	rawURL := base + path
	var bodyReader io.Reader
	if len(bodyJSON) > 0 {
		bodyReader = strings.NewReader(string(bodyJSON))
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, rawURL, bodyReader)
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Forwarded-Proto", "https")

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	return body, resp.StatusCode, err
}

// AuthorizedDelete performs a DELETE against the controller API using the session token.
func (s *Session) AuthorizedDelete(ctx context.Context, path string) ([]byte, int, error) {
	s.mu.RLock()
	base := s.baseURL
	token := s.token
	s.mu.RUnlock()

	rawURL := base + path
	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, rawURL, nil)
	if err != nil {
		return nil, 0, err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("X-Forwarded-Proto", "https")

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	return body, resp.StatusCode, err
}

// HasToken reports whether a controller session token is configured.
func (s *Session) HasToken() bool {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.token != ""
}


func normalizeBaseURL(raw string) string {
	trimmed := strings.TrimSpace(raw)
	if trimmed == "" {
		return defaultControllerURL
	}
	if !strings.Contains(trimmed, "://") {
		trimmed = "http://" + trimmed
	}
	u, err := url.Parse(trimmed)
	if err != nil || strings.TrimSpace(u.Host) == "" {
		return defaultControllerURL
	}
	u.Path = ""
	u.RawQuery = ""
	u.Fragment = ""
	return strings.TrimRight(u.String(), "/")
}
