// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ClearNetworkAssistantProcessEvents():Promise<void>;

export function CloudflareSpeedTest(arg1:backend.CloudflareSpeedTestRequest):Promise<backend.CloudflareSpeedTestResponse>;

export function CreateProbeNode(arg1:string):Promise<backend.ProbeNode>;

export function EnableNetworkAssistantTUN():Promise<backend.NetworkAssistantStatus>;

export function ForceRefreshNetworkAssistantNodes(arg1:string,arg2:string):Promise<void>;

export function ForceRefreshProbeDNSCache(arg1:string,arg2:string):Promise<string>;

export function GetAIDebugListenEnabled():Promise<boolean>;

export function GetDeletedProbeNodeNos():Promise<Array<number>>;

export function GetGlobalControllerIP():Promise<string>;

export function GetGlobalControllerURL():Promise<string>;

export function GetLatestGitHubRelease(arg1:string):Promise<backend.ReleaseInfo>;

export function GetLatestGitHubReleaseViaProxy(arg1:string,arg2:string,arg3:string):Promise<backend.ReleaseInfo>;

export function GetLocalManagerLogs(arg1:number,arg2:number,arg3:string):Promise<backend.LogViewResponse>;

export function GetLocalPrivateKeyStatus():Promise<backend.PrivateKeyStatus>;

export function GetManagerUpgradeProgress():Promise<backend.ManagerUpgradeProgress>;

export function GetManagerVersion():Promise<string>;

export function GetNetworkAssistantDNSUpstreamConfig():Promise<backend.NetworkAssistantDNSUpstreamConfig>;

export function GetNetworkAssistantLogs(arg1:number):Promise<backend.NetworkAssistantLogResponse>;

export function AppendNetworkAssistantDebugLog(arg1:string,arg2:string):Promise<void>;

export function GetNetworkAssistantRuleConfig():Promise<backend.NetworkAssistantRuleConfig>;

export function GetNetworkAssistantStatus():Promise<backend.NetworkAssistantStatus>;

export function GetProbeLinkChainsCache():Promise<Array<backend.ProbeLinkChainCacheItem>>;

export function GetProbeNodes():Promise<Array<backend.ProbeNode>>;

export function Greet(arg1:string):Promise<string>;

export function InstallNetworkAssistantTUN():Promise<backend.NetworkAssistantStatus>;

export function ListNetworkAssistantProcesses():Promise<Array<backend.NetworkProcessInfo>>;

export function MarkProbeNodeDeleted(arg1:number):Promise<void>;

export function PingProbeChain(arg1:string):Promise<backend.ProbeChainPingResult>;

export function PingProbeLinkSession():Promise<backend.ProbeLinkConnectResult>;

export function QueryNetworkAssistantDNSCache(arg1:string):Promise<Array<backend.NetworkAssistantDNSCacheEntry>>;

export function QueryNetworkAssistantProcessEvents(arg1:number):Promise<Array<backend.NetworkProcessEvent>>;

export function ReplaceProbeNodes(arg1:Array<backend.ProbeNode>):Promise<Array<backend.ProbeNode>>;

export function RestoreDeletedProbeNode(arg1:number):Promise<void>;

export function RestoreNetworkAssistantDirect():Promise<backend.NetworkAssistantStatus>;

export function SetAIDebugListenEnabled(arg1:boolean):Promise<boolean>;

export function SetGlobalControllerIP(arg1:string):Promise<string>;

export function SetGlobalControllerURL(arg1:string):Promise<string>;

export function SetNetworkAssistantDNSUpstreamConfig(arg1:backend.NetworkAssistantDNSUpstreamConfig):Promise<void>;

export function SetNetworkAssistantMode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.NetworkAssistantStatus>;

export function SetNetworkAssistantRulePolicy(arg1:string,arg2:string,arg3:string):Promise<backend.NetworkAssistantRuleConfig>;

export function SignNonceWithLocalKey(arg1:string):Promise<string>;

export function StartNetworkAssistantProcessMonitor():Promise<void>;

export function StartProbeLinkSession(arg1:string,arg2:string,arg3:string,arg4:number):Promise<backend.ProbeLinkConnectResult>;

export function StopNetworkAssistantProcessMonitor():Promise<void>;

export function StopProbeLinkSession():Promise<boolean>;

export function SyncNetworkAssistant(arg1:string,arg2:string):Promise<backend.NetworkAssistantStatus>;

export function TestProbeLink(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<backend.ProbeLinkConnectResult>;

export function UpdateProbeNode(arg1:number,arg2:string,arg3:boolean):Promise<backend.ProbeNode>;

export function UpdateProbeNodeSettings(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<backend.ProbeNode>;

export function UpgradeManagerDirect(arg1:string):Promise<backend.ManagerUpgradeResult>;

export function UpgradeManagerViaProxy(arg1:string,arg2:string,arg3:string):Promise<backend.ManagerUpgradeResult>;

export function UploadNetworkAssistantRuleRoutes(arg1:string,arg2:string):Promise<string>;
