// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalPrivateKeyStatus() {
  return window['go']['main']['App']['GetLocalPrivateKeyStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SignNonceWithLocalKey(arg1) {
  return window['go']['main']['App']['SignNonceWithLocalKey'](arg1);
}
